/**
 * Form Fields Configuration
 * Auto-generated — edit data_list / class / is_visible as needed.
 */

export default [
	{
		name: "title",
		label: "Enter Title",
		type: "text",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	
	{
		name: "banner_image",
		label: "Upload Banner Image",
		type: "file",
		multiple: false,
		accept: "image/*",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "banner_image_mobile",
		label: "Upload Banner Image Mobile",
		type: "file",
		multiple: false,
		accept: "image/*",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "button_text",
		label: "Enter Button Text",
		type: "text",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "button_link",
		label: "Enter Button Link",
		type: "url",
		placeholder: "https://example.com",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "alt_text",
		label: "Enter Alt Text",
		type: "text",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "start_date",
		label: "Enter Start Date",
		type: "datetime-local",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "end_date",
		label: "Enter End Date",
		type: "datetime-local",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "is_active",
		label: "Select Is Active",
		type: "select",
		label: "Select Is Active",
		multiple: false,
		data_list: [
			{ label: "Yes", value: "yes" },
			{ label: "No", value: "no" },
		],
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "display_order",
		label: "Enter Display Order",
		type: "number",
		step: "1",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "background_color",
		label: "Enter Background Color",
		type: "color",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "description",
		label: "Enter Description",
		type: "textarea",
		rows: 4,
		value: "",
		is_visible: true,
		class: "col-md-12",
	},
];
