/**
 * Form Fields Configuration
 * Auto-generated — edit data_list / class / is_visible as needed.
 */

export default [
	{
		name: "order_number",
		label: "Enter Order Number",
		type: "text",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "customer_name",
		label: "Enter Customer Name",
		type: "text",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "customer_phone",
		label: "Enter Customer Phone",
		type: "tel",
		placeholder: "+1 (555) 000-0000",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "customer_email",
		label: "Enter Customer Email",
		type: "email",
		placeholder: "example@domain.com",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "delivery_address",
		label: "Enter Delivery Address",
		type: "textarea",
		rows: 4,
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "delivery_area_id",
		label: "Select Delivery Area",
		type: "select",
		multiple: false,
		data_list: [],
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "delivery_district",
		label: "Enter Delivery District",
		type: "text",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "delivery_thana",
		label: "Enter Delivery Thana",
		type: "text",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "delivery_village",
		label: "Enter Delivery Village",
		type: "text",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "delivery_date",
		label: "Enter Delivery Date",
		type: "date",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "delivered_date",
		label: "Enter Delivered Date",
		type: "date",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "subtotal",
		label: "Enter Subtotal",
		type: "text",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "shipping_charge",
		label: "Enter Shipping Charge",
		type: "text",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "discount_amount",
		label: "Enter Discount Amount",
		type: "text",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "promo_code_used",
		label: "Enter Promo Code Used",
		type: "text",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "total_amount",
		label: "Enter Total Amount",
		type: "text",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "payment_method",
		label: "Enter Payment Method",
		type: "text",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "payment_status",
		label: "Select Payment Status",
		type: "select",
		label: "Select Payment Status",
		multiple: false,
		data_list: [
			{ label: "Pending", value: "pending" },
			{ label: "Completed", value: "completed" },
			{ label: "Failed", value: "failed" },
			{ label: "Refunded", value: "refunded" },
		],
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "order_status",
		label: "Select Order Status",
		type: "select",
		label: "Select Order Status",
		multiple: false,
		data_list: [
			{ label: "Pending", value: "pending" },
			{ label: "Confirmed", value: "confirmed" },
			{ label: "Processing", value: "processing" },
			{ label: "Shipped", value: "shipped" },
			{ label: "Delivered", value: "delivered" },
			{ label: "Cancelled", value: "cancelled" },
			{ label: "Returned", value: "returned" },
		],
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "special_notes",
		label: "Enter Special Notes",
		type: "textarea",
		rows: 4,
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "admin_notes",
		label: "Enter Admin Notes",
		type: "textarea",
		rows: 4,
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "ip_address",
		label: "Enter Ip Address",
		type: "text",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "source",
		label: "Select Source",
		type: "select",
		label: "Select Source",
		multiple: false,
		data_list: [
			{ label: "Website", value: "website" },
			{ label: "Mobile", value: "mobile" },
			{ label: "Whatsapp", value: "whatsapp" },
			{ label: "Phone", value: "phone" },
		],
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
];
