/**
 * Form Fields Configuration
 * Auto-generated — edit data_list / class / is_visible as needed.
 */

export default [
	{
		name: "code",
		label: "Enter Code",
		type: "text",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "description",
		label: "Enter Description",
		type: "text",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "discount_type",
		label: "Select Discount Type",
		type: "select",
		label: "Select Discount Type",
		multiple: false,
		data_list: [
			{ label: "Percentage", value: "percentage" },
			{ label: "Fixed", value: "fixed" },
		],
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "discount_value",
		label: "Enter Discount Value",
		type: "text",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "minimum_order_amount",
		label: "Enter Minimum Order Amount",
		type: "text",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "maximum_discount_amount",
		label: "Enter Maximum Discount Amount",
		type: "text",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "applicable_categories",
		label: "Enter Applicable Categories",
		type: "textarea",
		rows: 4,
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "max_usage",
		label: "Enter Max Usage",
		type: "number",
		step: "1",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "current_usage",
		label: "Enter Current Usage",
		type: "number",
		step: "1",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "max_usage_per_customer",
		label: "Enter Max Usage Per Customer",
		type: "number",
		step: "1",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "valid_from",
		label: "Enter Valid From",
		type: "datetime-local",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "valid_until",
		label: "Enter Valid Until",
		type: "datetime-local",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "is_active",
		label: "Select Is Active",
		type: "select",
		label: "Select Is Active",
		multiple: false,
		data_list: [
			{ label: "Yes", value: "yes" },
			{ label: "No", value: "no" },
		],
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
];
